// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4rW7YoeXM4wavt1KYE2HeBghOQnCC7xA',
    appId: '1:945144457647:web:83dcde7d3a2d30bb76275a',
    messagingSenderId: '945144457647',
    projectId: 'ennatodo-project',
    authDomain: 'ennatodo-project.firebaseapp.com',
    storageBucket: 'ennatodo-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCC6EhuCrFbXHUwWPl-An0d3IJmzN9dU',
    appId: '1:945144457647:android:f668a4fad2b3a3a876275a',
    messagingSenderId: '945144457647',
    projectId: 'ennatodo-project',
    storageBucket: 'ennatodo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASK78flNN8m02eH7c3waHixsvC3gjzp2I',
    appId: '1:945144457647:ios:92b2c3b22a7c1ed376275a',
    messagingSenderId: '945144457647',
    projectId: 'ennatodo-project',
    storageBucket: 'ennatodo-project.firebasestorage.app',
    iosBundleId: 'com.example.ennatodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASK78flNN8m02eH7c3waHixsvC3gjzp2I',
    appId: '1:945144457647:ios:92b2c3b22a7c1ed376275a',
    messagingSenderId: '945144457647',
    projectId: 'ennatodo-project',
    storageBucket: 'ennatodo-project.firebasestorage.app',
    iosBundleId: 'com.example.ennatodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4rW7YoeXM4wavt1KYE2HeBghOQnCC7xA',
    appId: '1:945144457647:web:e4a31106c279628676275a',
    messagingSenderId: '945144457647',
    projectId: 'ennatodo-project',
    authDomain: 'ennatodo-project.firebaseapp.com',
    storageBucket: 'ennatodo-project.firebasestorage.app',
  );
}
